# Generated by Django 3.1.7 on 2021-04-03 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dossier', '0002_auto_20210403_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_type', models.CharField(max_length=200)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dossier.dossier')),
            ],
        ),
    ]
