# Generated by Django 3.1.5 on 2021-04-09 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dossier', '0003_auto_20210403_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('photo', models.ImageField(blank=True, upload_to='photos', verbose_name='Фото')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='dossier',
        ),
        migrations.AddField(
            model_name='dossier',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dossier.category', verbose_name='Категория граждан'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='prop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dossier.property', verbose_name='Имущество'),
        ),
    ]
