# Generated by Django 3.1.5 on 2021-04-09 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dossier', '0004_auto_20210409_0810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Разряд кента', 'verbose_name_plural': 'Разряды кентов'},
        ),
        migrations.AlterModelOptions(
            name='dossier',
            options={'ordering': ['name'], 'verbose_name': 'Кент', 'verbose_name_plural': 'Кенты'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['name'], 'verbose_name': 'Экипировка'},
        ),
        migrations.AddField(
            model_name='category',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dossier.dossier', verbose_name='Категория граждан'),
        ),
    ]
