# Generated by Django 3.1.5 on 2021-04-09 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dossier', '0005_auto_20210409_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='prop',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='dossier.property', verbose_name='Имущество'),
        ),
    ]
