# Generated by Django 3.1.7 on 2021-04-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier', '0007_auto_20210410_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat',
            field=models.ManyToManyField(blank=True, null=True, to='dossier.Dossier', verbose_name='Категория граждан'),
        ),
    ]
