# Generated by Django 3.1.5 on 2021-04-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier', '0010_auto_20210410_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Класс объекта', 'verbose_name_plural': 'Класс объекта'},
        ),
        migrations.AlterModelOptions(
            name='dossier',
            options={'ordering': ['name'], 'verbose_name': 'Объект', 'verbose_name_plural': 'Объект'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['name'], 'verbose_name': 'Снаряжение', 'verbose_name_plural': 'Снаряжения'},
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_type',
            field=models.CharField(max_length=200, verbose_name='Класс объекта'),
        ),
    ]
