# Generated by Django 3.1.5 on 2021-04-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier', '0013_auto_20210417_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossier',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='dossier',
            field=models.ManyToManyField(blank=True, to='dossier.Dossier'),
        ),
    ]
