# Generated by Django 3.1.5 on 2021-04-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier', '0014_auto_20210417_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_description',
            field=models.CharField(max_length=200, null=True, verbose_name='Описание класса'),
        ),
    ]
